### ISSUE TITLE
How to show new line with long text and print table from struct by reflect?

### ISSUE THREAD

**Issue by ddkwork** [splace/table#1]

**Comment by splace** [comment]
not sure what you mean.  this package converts a table in TSV to a smart looking table with lots of formatting/rearranging options.

however....

you can use standard go lib (fmt) to make the TSV easily for a known structure.

if you really need a general solution, using reflect, it would need to be coded, not hard, maybe someone already did.

**Comment by ddkwork** [comment]
> not sure what you mean.  this package converts a table in TSV to a smart looking table with lots of formatting/rearranging options.
> 
> however....
> 
> you can use standard go lib (fmt) to make the TSV easily for a known structure.
> 
> if you really need a general solution, using reflect, it would need to be coded, not hard, maybe someone already did.
> 

My means is how to set table field as MultiLine,for example the stack or hex dump and too  longer string?

Now i use go script running genrated table go codes, if use reflect it will be cancel.

**Comment by ddkwork** [comment]
Another problem is the align is falid on linux container, for example termux linux.

![Screenshot_20220429_123301_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/165885698-576f396a-c797-4b69-a1ea-2d5fd05f9989.jpg)

**Comment by splace** [comment]
can you post some TSV's that has this problem?
